#!/bin/sh

REV="-H iot2000:rev1"
TMPFILE="/tmp/update.swu"
LOGFILE="/var/log/swupdate.log"

start() {
    wget http://update.predictablefarm.net/predictable-farm/update.swu -O ${TMPFILE}

    swupdate_unstripped ${REV} -i ${TMPFILE} -c | grep 'successfully' &> /dev/null

    if [ $? == 0 ]; then
        echo "File found, and correct, updating"
        swupdate_unstripped ${REV} -v -i ${TMPFILE} >> ${LOGFILE}
        echo "Removing update file ${TMPFILE}"
        rm -rf ${TMPFILE}
    else
        echo "Update is not correct, aborting"
    fi
}

case "$1" in
  start)
    start
    ;;
  *)
    echo "Usage: $0 {start}"
esac