#!/bin/sh

APPDIR="/home/root/predictable-farm"
TMPFILE="/tmp/update.swu"
LOGFILE="/var/log/swupdate.log"

check_update() {
    # CHANGE ME
    wget http://my.predictablefarm.domain/update.swu -O ${TMPFILE}

    swupdate_unstripped -i ${TMPFILE} -c | grep 'successfully' &> /dev/null

    if [ $? == 0 ]; then
        echo "File found, and correct, updating"
        swupdate_unstripped -v -i ${TMPFILE} >> ${LOGFILE}
        echo "Removing update file ${TMPFILE}"
        rm -rf ${TMPFILE}
    else
        echo "Update is not correct, aborting"
    fi
}

start() {
    check_update

    cd ${APPDIR}

    # We need to source the environment vars since
    # we are in a non-login, non-interactive process
    . /etc/profile.d/env_vars.sh

    if [ -f forever.json ]; then
        echo "Starting Predictable-farm ..."
        ./scripts/start.sh
    fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    ;;
  *)
    echo "Usage: $0 {start}"
esac